apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: change-image-tag
spec:
  workspaces:
  - name: source
  params:
    - name: manifest
      description: The manifest file to apply
      type: string
      default: "./chapter10/clouds-api-gitops/overlays/qa/kustomization.yaml"
    - name: new-tag
      description: The manifest file to apply
      type: string      
  steps:
    - name: commit-push-changes-gitops
      image: alpine/git:v2.30.2
      workingDir: "$(workspaces.config-source.path)"
      script: |
        #!/usr/bin/env sh
        set -e
    
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_*
    
        git config --global user.email "tekton@tekton.dev"
        git config --global user.name "Tekton Pipeline"
        git add .
        git commit --allow-empty -m "[Tekton] updating $(params.environment)"
        git push origin main
