apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-v1-pipelinerun
spec:
  pipelineRef:
    name: build-app
  params:
  - name: git-url
    value: https://github.com/giofontana/Openshift-Multi-Cluster-management.git
  - name: git-revision
    value: dev
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/cicd/clouds-api:v1.0   
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
