apiVersion: tekton.dev/v1beta1 
kind: TaskRun 
metadata: 
  name: git-clone 
spec: 
  taskRef: 
    name: git-clone 
    kind: ClusterTask 
  params: 
  - name: url 
    value: "https://github.com/giofontana/Openshift-Multi-Cluster-management.git" 
  - name: subdirectory 
    value: "" 
  - name: deleteExisting 
    value: "true" 
  - name: revision 
    value: "main" 
  workspaces: 
  - name: output 
    persistentVolumeClaim: 
      claimName: source-pvc  
