apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: qa

namespace: clouds-api-qa

resources:
  - namespace.yaml
  - ../../base

images:
- name: quay.io/gfontana/clouds-api
  newName: image-registry.openshift-image-registry.svc:5000/cicd/clouds-api
  newTag: v2.0
